# Generated by Django 2.0.6 on 2019-02-23 18:25

import amcat_enhance_login.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcat_enhance_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='amcat_login_with_face_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('student_pic', models.ImageField(help_text='Allowed Extension Are Only .jpeg', upload_to='pic_folder/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg']), amcat_enhance_login.models.max_size_allowed])),
                ('course', models.CharField(choices=[('btech', 'B-Tech'), ('bcom', 'B-Com'), ('mba', 'MBA')], default='btech', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='amcat_login_with_face_traker',
        ),
    ]
