# Generated by Django 2.0.6 on 2019-02-23 18:54

import amcat_enhance_login.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcat_enhance_login', '0002_auto_20190223_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcat_login_with_face_tracker',
            name='student_pic',
            field=models.ImageField(help_text='Allowed Extension Are Only .jpeg', upload_to='pic_folder/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png']), amcat_enhance_login.models.max_size_allowed]),
        ),
    ]
