# Generated by Django 2.0.6 on 2019-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcat_enhance_login', '0003_auto_20190224_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amcat_login_with_face_tracker',
            name='student_pic',
        ),
        migrations.AddField(
            model_name='amcat_login_with_face_tracker',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
